### ISSUE TITLE
Plugctl sometimes crashes with an "index out of range error"

### ISSUE THREAD

**Issue by joyrider3774** [42wim/plugctl#2]
Happens on android as well as on windows.

this is a screenshot of the error happening on android with plugctl 0.21
![knipsel](https://cloud.githubusercontent.com/assets/10714776/5908617/749b3f58-a5a9-11e4-9c3f-f29f76320430.PNG)

**Comment by joyrider3774** [comment]
did not notice the git commit's but it seems this one might be fixed with the latest version, i wasn't running the latest version before.

**Comment by 42wim** [comment]
Is fixed in previous commit, let me know if you still have issues with latest version
